version: '3'
services:
  ros:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../ros_ws:/ros_ws
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    privileged: true 